
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu
  namespace: nodejs-ns
spec:
  mode: one
  selector:
    namespaces:
      - nodejs-app
    labelSelectors:
      app: nodeapp
  stressors:
    cpu:
      workers: 2
  duration: "60s"
