apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapp-hpa
  namespace: nodejs-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50