apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: nodejs-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080  # Valid NodePort range: 30000–32767